# ==========================================
# CONFIGURACIÓN DEL SERVIDOR
# ==========================================
server.port=8080

# ==========================================
# CONFIGURACIÓN DE LA BASE DE DATOS (POSTGRESQL)
# ==========================================
# URL de conexión 
spring.datasource.url=jdbc:postgresql://localhost:5432/civa
spring.datasource.username=Civa

spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================
# Dialecto para optimizar las consultas en PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Muestra las consultas SQL en la consola 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Estrategia de generación de tablas: 
# 'update' crea o actualiza las tablas basándose en tus entidades
spring.jpa.hibernate.ddl-auto=update

# Evita un error común de Hibernate con la inicialización diferida 
spring.jpa.open-in-view=false